version: "1.0"

sources:
  # =============================================================================
  # PREMIUM THREAT INTELLIGENCE SOURCES (Highest Actionable Value)
  # =============================================================================
  
  # Cisco Talos Blog - Fixed RSS URL and SSL handling
  - id: "cisco_talos"
    name: "Cisco Talos Intelligence Blog"
    url: "https://blog.talosintelligence.com/"
    rss_url: "https://blog.talosintelligence.com/rss/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["blog.talosintelligence.com"]
      post_url_regex: ["^https://blog\\.talosintelligence\\.com/.*"]
      robots:
        enabled: true
        user_agent: "CTIScraper/2.0"
        respect_delay: true
        max_requests_per_minute: 10
        crawl_delay: 1.0
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: 
          - "meta[property='article:published_time']::attr(content)"
          - "time[datetime]::attr(datetime)"
        body_selectors: ["article", "main", ".content", ".post-content"]
        author_selectors: ["meta[name='author']::attr(content)", ".author-name"]
    description: "High-quality threat intelligence with actionable IOCs and TTPs"

  # Huntress Blog - Fixed RSS URL
  - id: "huntress_blog"
    name: "Huntress Cybersecurity Blog"
    url: "https://www.huntress.com/blog"
    rss_url: "https://www.huntress.com/blog/rss.xml"  # Fixed RSS URL
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["huntress.com"]
      post_url_regex: ["^https://www\\.huntress\\.com/blog/.*"]
      robots:
        enabled: true
        user_agent: "CTIScraper/2.0"
        respect_delay: true
        max_requests_per_minute: 8
        crawl_delay: 2.0
      extract:
        prefer_jsonld: true
        title_selectors: ["h1.landing-banner-heading-h1", "h1.blog", ".landing-banner-heading-h1", "h1"]
        body_selectors: [".blog-post-summary", ".blog-post-summary-main", ".blog-main-section", ".post-wrapper", "main"]
        author_selectors: [".author-name", ".author-link", ".authors-wrapper .author-item", ".attribution-container"]
        date_selectors: [".published-text", ".blog-date-breadcrumb", "time", ".date", "[datetime]"]
    description: "Excellent DFIR and threat hunting content with actionable intelligence"

  # Mandiant Threat Research
  - id: "mandiant_research"
    name: "Mandiant Threat Research"
    url: "https://www.mandiant.com/resources/blog"
    rss_url: "https://www.mandiant.com/resources/blog/rss.xml"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["mandiant.com"]
      post_url_regex: ["^https://www\\.mandiant\\.com/resources/blog/.*"]
      robots:
        enabled: true
        user_agent: "CTIScraper/2.0"
        respect_delay: true
        max_requests_per_minute: 6
        crawl_delay: 3.0
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "High-quality APT research and threat intelligence"

  # Palo Alto Unit42
  - id: "palo_alto_unit42"
    name: "Palo Alto Unit42"
    url: "https://unit42.paloaltonetworks.com/"
    rss_url: "https://unit42.paloaltonetworks.com/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["unit42.paloaltonetworks.com"]
      post_url_regex: ["^https://unit42\\.paloaltonetworks\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Exceptional threat research with detailed IOCs and TTPs"

  # Kaspersky Securelist
  - id: "kaspersky_securelist"
    name: "Kaspersky Securelist"
    url: "https://securelist.com/"
    rss_url: "https://securelist.com/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["securelist.com"]
      post_url_regex: ["^https://securelist\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Excellent malware analysis and APT research"

  # ESET Research
  - id: "eset_research"
    name: "ESET Research"
    url: "https://www.welivesecurity.com/category/research/"
    rss_url: "https://www.welivesecurity.com/category/research/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["welivesecurity.com"]
      post_url_regex: ["^https://www\\.welivesecurity\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Strong malware research with technical details"

  # Recorded Future
  - id: "recorded_future"
    name: "Recorded Future"
    url: "https://www.recordedfuture.com/"
    rss_url: "https://www.recordedfuture.com/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["recordedfuture.com"]
      post_url_regex: ["^https://www\\.recordedfuture\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "High-quality threat intelligence and analysis"

  # SentinelOne Labs
  - id: "sentinelone_labs"
    name: "SentinelOne Labs"
    url: "https://www.sentinelone.com/labs/"
    rss_url: "https://www.sentinelone.com/labs/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["sentinelone.com"]
      post_url_regex: ["^https://www\\.sentinelone\\.com/labs/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Good threat research with detection context"

  # Elastic Security Labs
  - id: "elastic_security_labs"
    name: "Elastic Security Labs"
    url: "https://www.elastic.co/security-labs/"
    rss_url: "https://www.elastic.co/security-labs/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["elastic.co"]
      post_url_regex: ["^https://www\\.elastic\\.co/security-labs/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Detection-focused research with hunting queries"

  # Picus Security Blog
  - id: "picus_security_blog"
    name: "Picus Security Blog"
    url: "https://www.picussecurity.com/resource/blog"
    rss_url: null  # No RSS feed available
    check_frequency: 3600  # 1 hour - web scraping only
    active: true
    config:
      allow: ["picussecurity.com"]
      post_url_regex: ["^https://www\\.picussecurity\\.com/resource/blog/.*"]
      robots:
        enabled: true
        user_agent: "CTIScraper/2.0"
        respect_delay: true
        max_requests_per_minute: 5
        crawl_delay: 3.0
      extract:
        prefer_jsonld: false  # No structured data available
        title_selectors: 
          - "h1 span#hs_cos_wrapper_name"
          - "h1"
          - "meta[property='og:title']::attr(content)"
          - "title"
        date_selectors: 
          - "meta[property='article:published_time']::attr(content)"
          - "meta[name='article:published_time']::attr(content)"
          - "time[datetime]::attr(datetime)"
          - ".published-date"
        body_selectors: 
          - ".hs_cos_wrapper_type_rich_text"
          - ".blog-content"
          - "article"
          - "main"
          - ".content"
        author_selectors: 
          - ".author-name"
          - ".byline"
          - "meta[name='author']::attr(content)"
    description: "Security validation and breach simulation research with APT analysis"

  # Check Point Research
  - id: "checkpoint_research"
    name: "Check Point Research"
    url: "https://research.checkpoint.com/"
    rss_url: "https://research.checkpoint.com/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["research.checkpoint.com"]
      post_url_regex: ["^https://research\\.checkpoint\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Solid threat research with technical analysis"

  # =============================================================================
  # NEWS AND ANALYSIS SOURCES (Good Coverage)
  # =============================================================================

  # The Hacker News
  - id: "the_hacker_news"
    name: "The Hacker News"
    url: "https://thehackernews.com/"
    rss_url: "https://feeds.feedburner.com/TheHackersNews"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["thehackernews.com"]
      post_url_regex: ["^https://thehackernews\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Comprehensive cybersecurity news coverage"

  # Bleeping Computer
  - id: "bleeping_computer"
    name: "Bleeping Computer"
    url: "https://www.bleepingcomputer.com/"
    rss_url: "https://www.bleepingcomputer.com/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["bleepingcomputer.com"]
      post_url_regex: ["^https://www\\.bleepingcomputer\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Good security news with malware analysis"

  # Dark Reading
  - id: "dark_reading"
    name: "Dark Reading"
    url: "https://www.darkreading.com/"
    rss_url: "https://www.darkreading.com/rss.xml"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["darkreading.com"]
      post_url_regex: ["^https://www\\.darkreading\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Professional cybersecurity news and analysis"

  # SecurityWeek
  - id: "securityweek"
    name: "SecurityWeek"
    url: "https://www.securityweek.com/"
    rss_url: "https://www.securityweek.com/feed/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["securityweek.com"]
      post_url_regex: ["^https://www\\.securityweek\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "General cybersecurity news and industry updates"

  # Infosecurity Magazine
  - id: "infosecurity_magazine"
    name: "Infosecurity Magazine"
    url: "https://www.infosecurity-magazine.com/"
    rss_url: "https://www.infosecurity-magazine.com/rss/news/"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["infosecurity-magazine.com"]
      post_url_regex: ["^https://www\\.infosecurity-magazine\\.com/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Security news and industry insights"

  # SANS Internet Storm Center
  - id: "sans_isc"
    name: "SANS Internet Storm Center"
    url: "https://isc.sans.edu/"
    rss_url: "https://isc.sans.edu/rssfeed.xml"
    check_frequency: 1800  # 30 minutes
    active: true
    config:
      allow: ["isc.sans.edu"]
      post_url_regex: ["^https://isc\\.sans\\.edu/.*"]
      extract:
        prefer_jsonld: true
        title_selectors: ["h1", "meta[property='og:title']::attr(content)"]
        date_selectors: ["meta[property='article:published_time']::attr(content)"]
        body_selectors: ["article", "main", ".content", ".post-content"]
    description: "Daily security incident analysis and threat intelligence"

  # =============================================================================
  # LEGACY SOURCES (Keep for compatibility)
  # =============================================================================

  # DFIR Report (existing)
  - id: "dfir_report"
    name: "The DFIR Report"
    url: "https://thedfirreport.com"
    rss_url: "https://thedfirreport.com/feed/"
    check_frequency: 1800  # 30 minutes
    active: true

  # CrowdStrike Blog (existing)
  - id: "crowdstrike_blog"
    name: "CrowdStrike Intelligence Blog"
    url: "https://www.crowdstrike.com/blog/"
    rss_url: "https://www.crowdstrike.com/blog/feed/"
    check_frequency: 1800  # 30 minutes
    active: true

  # Microsoft Security Response Center (existing)
  - id: "microsoft_security"
    name: "Microsoft Security Response Center"
    url: "https://msrc.microsoft.com/blog/"
    rss_url: "https://msrc.microsoft.com/blog/feed/"
    check_frequency: 3600  # 1 hour
    active: true

  # FireEye/Mandiant Blog (existing)
  - id: "fireeye_blog"
    name: "FireEye Threat Research"
    url: "https://www.mandiant.com/resources/blog"
    rss_url: "https://www.mandiant.com/resources/blog/rss.xml"
    check_frequency: 1800
    active: true

  # SpecterOps Blog (existing)
  - id: "specterops_blog"
    name: "SpecterOps Blog"
    url: "https://posts.specterops.io/"
    rss_url: "https://posts.specterops.io/feed/"
    check_frequency: 1800  # 30 minutes - Tier 1 priority
    active: true
    config:
      content_selector: "div.blog-content, article"
    description: "Advanced adversary tradecraft and detection research - premium huntable intel"

  # Red Canary Blog (existing)
  - id: "red_canary_blog"
    name: "Red Canary Blog"
    url: "https://redcanary.com/blog/"
    rss_url: "https://redcanary.com/blog/feed/"
    check_frequency: 1800  # 30 minutes - Tier 1 priority
    active: true
    config:
      content_selector: "div.blog-content, article"
    description: "Detection-focused research with actionable hunting techniques and IOCs"
